# Generated by Django 4.0.1 on 2022-01-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reply_comment_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
    ]
